name: Generate MiSTer latest repo
on:
  workflow_dispatch:

permissions: write-all
jobs:
  mister-repo:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    steps:
      - uses: actions/checkout@v2
      - name: Get latest Zaparoo release
        id: zaparooreleaseinfo
        uses: cardinalby/git-get-release-action@v1
        with:
          latest: true
          repo: ZaparooProject/zaparoo-core
      - name: Create repo database
        run: |
          python3 scripts/mister/repo/generate.py ${{ steps.zaparooreleaseinfo.outputs.tag_name }}
      - name: Commit repo database
        uses: EndBug/add-and-commit@v9
        with:
          add: scripts/mister/repo/tapto.json -f -A
